---
name: Push

'on':
  push:
    branches:
      - '*'
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:

  build:

    name: Build
    runs-on: ubuntu-22.04

    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Execute YAMLlint
        uses: ibiqlik/action-yamllint@v3
